repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_docs
        args:
          - --hook-config=markdown
          - --hook-config=--add-to-exiting-file=true
          - --hook-config=--path-to-file=README.md
          - --hook-config=--create-file-if-not-exist=true
          - --args=--hide-empty
      - id: terraform_tflint
        args:
          - --args=--enable-plugin=aws
          - --args=--disable-rule=terraform_module_pinned_source
          - --args=--disable-rule=aws_lambda_function_invalid_runtime
